import { test, expect } from '@playwright/test'
test('create, autosave, reload, complete, drag, filter and delete a task', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/')
  await expect(page.locator('.task-card')).toHaveCount(13)
  await page.getByRole('button', { name: 'Задача N', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Задача', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Название', { exact: true }).fill('Проверка прототипа')
  await dialog.getByLabel('Описание', { exact: true }).fill('Автосохранение работает')
  await dialog.getByLabel('Заметки', { exact: true }).fill('Важная заметка')
  await dialog.getByLabel('Начало', { exact: true }).fill('17:00')
  await dialog.getByLabel('Окончание', { exact: true }).fill('18:30')
  await dialog.getByRole('button', { name: 'Закрыть панель' }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  const card = page
    .locator('.task-card')
    .filter({ has: page.getByRole('button', { name: 'Проверка прототипа', exact: true }) })
  await expect(card).toContainText('17:00 – 18:30')
  await card.hover()
  await card.getByRole('button', { name: 'Выполнить: Проверка прототипа', exact: true }).click()
  await expect(card).toHaveClass(/completed/)
  const handle = card.getByRole('button', { name: 'Перенести: Проверка прототипа' })
  const source = await handle.boundingBox()
  const target = await page.locator('.day-column').last().boundingBox()
  if (!source || !target) throw new Error('Missing drag positions')
  await page.mouse.move(source.x + source.width / 2, source.y + source.height / 2)
  await page.mouse.down()
  await page.mouse.move(target.x + target.width / 2, source.y + source.height / 2, { steps: 15 })
  await page.mouse.up()
  await expect(
    page
      .locator('.day-column')
      .last()
      .getByRole('button', { name: 'Проверка прототипа', exact: true }),
  ).toBeVisible()
  await page.getByLabel('Поиск задач', { exact: true }).fill('Важная заметка')
  await expect(page.locator('.task-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Проверка прототипа', exact: true }).click()
  await expect(dialog.getByLabel('Описание', { exact: true })).toHaveValue(
    'Автосохранение работает',
  )
  await dialog.getByRole('button', { name: 'Удалить задачу', exact: true }).click()
  await dialog.getByRole('button', { name: 'Да, удалить', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('.task-card')).toHaveCount(0)
  expect(errors).toEqual([])
})
test('week navigation, themes, assistant and narrow screen', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.task-card')).toHaveCount(13)
  await page.getByRole('button', { name: 'Следующая неделя' }).click()
  await expect(page.locator('.task-card')).toHaveCount(0)
  await page.getByRole('button', { name: 'Сегодня', exact: true }).click()
  await expect(page.locator('.task-card')).toHaveCount(13)
  await page.getByRole('button', { name: 'Тёмная тема', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Открыть AI Assistant' }).click()
  await page.getByRole('button', { name: /Что у меня завтра/ }).click()
  await expect(page.locator('.assistant-answer')).not.toBeEmpty()
  await page.getByRole('button', { name: /Найти два свободных часа/ }).click()
  await expect(page.locator('.assistant-answer')).toContainText('Завтра')
  await page.getByRole('button', { name: 'Закрыть панель' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Задача N', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
})
test('rejects invalid time without silently losing a draft', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Задача N', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Начало', { exact: true }).fill('20:00')
  await dialog.getByRole('button', { name: 'Закрыть панель' }).click()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('alert')).toContainText('Окончание должно быть позже начала')
  await dialog.getByLabel('Окончание', { exact: true }).fill('21:00')
  await dialog.getByRole('button', { name: 'Закрыть панель' }).click()
  await expect(dialog).not.toBeVisible()
})
